import type { Metadata } from 'next';
import UuidGeneratorTool from '@/components/tools/UuidGeneratorTool';
import ToolShell from '@/components/tools/ToolShell';

export const metadata: Metadata = {
  title: 'UUID Generator — Free Online Tool',
  description: 'Generate secure, random UUID v4 values instantly in your browser. Free, fast, and privacy-friendly. Tool inputs are processed locally in your browser and are not intentionally transmitted to our servers.',
  alternates: { canonical: 'https://greptools.dev/tools/uuid-generator' },
  openGraph: {
    title: 'UUID Generator — Free Online Tool | grepTools',
    description: 'Generate secure, random UUID v4 values instantly in your browser. Free, fast, and privacy-friendly.',
    url: 'https://greptools.dev/tools/uuid-generator',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'UUID Generator | grepTools',
    description: 'Free browser-based UUID v4 generator. Generate up to 100 UUIDs instantly.',
  },
  keywords: ['uuid generator','generate uuid','uuid v4','random uuid','unique id generator','guid generator','uuid online'],
};

const faqSchema = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: [
    { '@type': 'Question', name: 'What is a UUID?', acceptedAnswer: { '@type': 'Answer', text: 'A UUID (Universally Unique Identifier) is a 128-bit value formatted as 32 hexadecimal digits separated by hyphens. It is designed to be globally unique without requiring a central registry.' } },
    { '@type': 'Question', name: 'What is UUID v4?', acceptedAnswer: { '@type': 'Answer', text: 'UUID v4 is generated using random or pseudo-random numbers. It is the most commonly used version for general-purpose unique identifiers like database primary keys and session tokens.' } },
    { '@type': 'Question', name: 'Can I generate multiple UUIDs at once?', acceptedAnswer: { '@type': 'Answer', text: 'Yes. Set the count field to any number from 1 to 100 and click Generate. All UUIDs are generated and displayed instantly.' } },
    { '@type': 'Question', name: 'Is this UUID generator secure?', acceptedAnswer: { '@type': 'Answer', text: 'Yes. This tool uses the browser\'s crypto.randomUUID() API where available, which is cryptographically secure. A fallback using Math.random() is used only on older browsers.' } },
    { '@type': 'Question', name: 'Is it free to use?', acceptedAnswer: { '@type': 'Answer', text: 'Yes, completely free. No account, no limits.' } },
  ],
};

export default function UuidGeneratorPage() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
      <ToolShell
        toolName="uuid-generator"
        toolIcon="⊕"
        heading="UUID Generator"
        intro="Generate secure UUIDs instantly in your browser. Free, fast, and privacy-friendly."
        chips={[
          { icon: '🔐', text: 'crypto.randomUUID' },
          { icon: '⚡', text: 'Instant' },
          { icon: '🔒', text: 'Local processing' },
          { icon: '📦', text: 'Batch up to 100' },
        ]}
        breadcrumbLabel="UUID Generator"
        faqs={[
          { q: 'What is a UUID?', a: 'A UUID (Universally Unique Identifier) is a 128-bit value formatted as 32 hexadecimal digits separated by hyphens. It is designed to be globally unique without requiring a central registry.' },
          { q: 'What is UUID v4?', a: 'UUID v4 is generated using random or pseudo-random numbers. It is the most commonly used version for general-purpose unique identifiers like database primary keys and session tokens.' },
          { q: 'Can I generate multiple UUIDs at once?', a: 'Yes. Set the count field to any number from 1 to 100 and click Generate. All UUIDs are generated and displayed instantly.' },
          { q: 'Is this UUID generator secure?', a: "Yes. This tool uses the browser's crypto.randomUUID() API where available, which is cryptographically secure. A fallback using Math.random() is used only on older browsers." },
          { q: 'Is it free to use?', a: 'Yes, completely free. No account, no limits.' },
        ]}
        relatedTools={[
          { name: 'JSON Formatter', href: '/tools/json-formatter', description: 'Format and validate JSON with syntax highlighting.', icon: '{}' },
          { name: 'Base64 Encoder/Decoder', href: '/tools/base64-encoder', description: 'Encode and decode Base64 strings instantly.', icon: '64' },
          { name: 'URL Encoder/Decoder', href: '/tools/url-encoder', description: 'Percent-encode and decode URLs safely.', icon: '%' },
          { name: 'Unix Timestamp Converter', href: '/tools/unix-timestamp-converter', description: 'Convert timestamps to readable dates.', icon: '⌚' },
        ]}
        aboutContent={
          <>
            <p>UUIDs generated by this tool follow the <strong>version 4</strong> standard (RFC 4122). The format is <code className="inline-code">xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx</code> where <code className="inline-code">y</code> is one of 8, 9, a, or b.</p>
            <p>The tool uses <code className="inline-code">crypto.randomUUID()</code> when available in modern browsers, providing cryptographically strong random values suitable for use as database primary keys, session IDs, correlation IDs, and more.</p>
          </>
        }
      >
        <UuidGeneratorTool />
      </ToolShell>
    </>
  );
}
