import type { Metadata } from 'next';
import Header from '@/components/site/Header';
import Footer from '@/components/home/Footer';

export const metadata: Metadata = {
  title: 'Terms of Service — grepTools',
  description: 'Terms of service for grepTools.dev. Understand your rights and limitations when using our tools.',
  robots: {
    index: false,
    follow: true,
  },
  alternates: {
    canonical: 'https://greptools.dev/terms',
  },
};

export default function TermsPage() {
  return (
    <>
      <Header />
      <div className="page-bg min-h-screen">
        <main className="page-main py-12 px-6">
          <div className="max-w-3xl mx-auto">
            {/* Header */}
            <div className="mb-10 text-center md:text-left">
              <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-100 tracking-tight mb-2">
                Terms of Service
              </h1>
              <p className="text-xs text-slate-500 font-mono">
                Last updated: May 31, 2026
              </p>
            </div>

            {/* Legal content panels */}
            <div className="space-y-6 text-sm text-slate-300 leading-relaxed font-sans select-text">
              {/* Service Description */}
              <div className="p-6 sm:p-8 rounded-xl bg-white/[0.015] border border-white/5 backdrop-blur-sm">
                <h2 className="text-lg font-bold text-slate-100 mb-4 flex items-center gap-2">
                  <span className="text-blue-400 font-mono">01.</span> Service Description
                </h2>
                <p className="mb-4">
                  Welcome to <strong>grepTools</strong> (&quot;we&quot;, &quot;our&quot;, or &quot;us&quot;). We provide a suite of 
                  free, browser-based developer utility tools, including JSON formatters, encoders, decoders, and generators.
                </p>
                <p>
                  By accessing or using our website at 
                  <a href="https://greptools.dev" className="text-blue-400 hover:underline ml-1">https://greptools.dev</a>, 
                  you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not access 
                  or use the site.
                </p>
              </div>

              {/* Acceptable Use */}
              <div className="p-6 sm:p-8 rounded-xl bg-white/[0.015] border border-white/5 backdrop-blur-sm">
                <h2 className="text-lg font-bold text-slate-100 mb-4 flex items-center gap-2">
                  <span className="text-blue-400 font-mono">02.</span> Acceptable Use
                </h2>
                <p className="mb-4">
                  You agree to use grepTools solely for lawful purposes. You are prohibited from:
                </p>
                <ul className="list-disc pl-5 space-y-2 text-slate-400">
                  <li>
                    Using the tools to process, encode, or convert malicious payloads, viruses, or illegal materials.
                  </li>
                  <li>
                    Attempting to disrupt or overload the site infrastructure through automated scripts or denial of service attacks.
                  </li>
                  <li>
                    Scraping or mirroring the site design and layouts to confuse users or serve phishing landing pages.
                  </li>
                </ul>
              </div>

              {/* Intellectual Property */}
              <div className="p-6 sm:p-8 rounded-xl bg-white/[0.015] border border-white/5 backdrop-blur-sm">
                <h2 className="text-lg font-bold text-slate-100 mb-4 flex items-center gap-2">
                  <span className="text-blue-400 font-mono">03.</span> Intellectual Property
                </h2>
                <p className="mb-4">
                  All rights, title, and interest in grepTools (including the logo, code, CSS styles, graphic assets, 
                  branding, and design elements) remain the exclusive property of <strong>[OWNER_NAME]</strong>.
                </p>
                <p>
                  Any inputs you supply to the tools and outputs generated by the tools belong entirely to you. We claim 
                  no ownership, license, or right over your processed code or text payloads.
                </p>
              </div>

              {/* No Warranty */}
              <div className="p-6 sm:p-8 rounded-xl bg-white/[0.015] border border-white/5 backdrop-blur-sm">
                <h2 className="text-lg font-bold text-slate-100 mb-4 flex items-center gap-2">
                  <span className="text-blue-400 font-mono">04.</span> Disclaimer of Warranties
                </h2>
                <p className="mb-4">
                  THE SERVICES ARE PROVIDED ON AN &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; BASIS. WE EXPRESSLY DISCLAIM ALL 
                  WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
                  PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
                </p>
                <p>
                  We make no guarantee that the tools will be 100% accurate, error-free, uninterrupted, or fully compatible 
                  with all data payloads. Use of the tool output is entirely at your own risk.
                </p>
              </div>

              {/* Limitation of Liability */}
              <div className="p-6 sm:p-8 rounded-xl bg-white/[0.015] border border-white/5 backdrop-blur-sm">
                <h2 className="text-lg font-bold text-slate-100 mb-4 flex items-center gap-2">
                  <span className="text-blue-400 font-mono">05.</span> Limitation of Liability
                </h2>
                <p>
                  IN NO EVENT SHALL GREPTOOLS OR [OWNER_NAME] BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, 
                  OR EXEMPLARY DAMAGES (INCLUDING LOSS OF PROFITS, DATA, USE, OR BUSINESS INTERRUPTION) ARISING OUT OF OR IN 
                  CONNECTION WITH YOUR USE OF OR INABILITY TO USE THE TOOLS, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
                </p>
              </div>

              {/* Governing Law */}
              <div className="p-6 sm:p-8 rounded-xl bg-white/[0.015] border border-white/5 backdrop-blur-sm">
                <h2 className="text-lg font-bold text-slate-100 mb-4 flex items-center gap-2">
                  <span className="text-blue-400 font-mono">06.</span> Governing Law & Changes
                </h2>
                <p className="mb-4">
                  These Terms of Service and any claim or dispute arising from the use of grepTools shall be governed by and 
                  construed in accordance with the laws of <strong>India</strong>, without giving effect to conflicts of law rules.
                </p>
                <p className="mb-4">
                  We reserve the right to modify these terms at any time. Your continued use of the site after updates are 
                  published constitutes acceptance of the modified terms.
                </p>
                <p className="mb-4">
                  For support or inquiries regarding these Terms, contact us at:
                </p>
                <div className="p-4 rounded bg-slate-900/60 border border-white/5 font-mono text-xs text-blue-400">
                  Email: [CONTACT_EMAIL]
                </div>
              </div>
            </div>
          </div>
        </main>
      </div>
      <Footer />
    </>
  );
}
